### PR TITLE
Better structure with namespaces. New like condition and select method. Updated orWhere and getStoreId method.

### PR DESCRIPTION
**Pull request by Timu57**
Hi,
thank you for this nice project.
I made some improvements.
Should not interfere with any code using this SleekDB.
Hope this can be merged or further improved before merging.

A little summary:

[ADDED]
like condition with regex;
ext-json to composer as required, because of json_encode and json_decode methods;
own file for every exception class, for better structure and easier usage outside of SleekDB;
namespaces to Traits and Exceptions;
[UPDATED]
file names of traits;
folder structure;
[FIXED]
missing @throws tags;
wrong behavior of verifyWhereConditions method if condition is not matched by any if statements;

### CODE REVIEW

**Comment by Timu57** [comment]
Added new select method to specify which fields should be in result.

The field names to select or exclude are separated with a space between.
To exclude a field prepend a - (minus) to the field name.

By default the field _id is always selected.
To exclude it specify -_id.

---
Example without select (nothing changed with this pr):
```php
$newsStore->where("_id", "=", 2)->fetch();
```
Output:
```php
[
  [
    "title" => "New Select Method",
    "content" => "Lorem Ipsum",
    "author" => "Max",
    "_id" => 2
  ]
]
```
---
## Example 1 - Select one field:
```php
$newsStore->select("title")->where("_id", "=", 2)->fetch();
```
Output:
```php
[[ "_id" => 2, "title" => "New Select Method" ]]
```
---
## Example 2 - Select two fields:
```php
$newsStore->select("title author")->where("_id", "=", 2)->fetch();
```
Output:
```php
[[ "_id" => 2, "title" => "New Select Method", "author" => "Max" ]]
```
---
## Example 3 - Don't select field:
```php
$newsStore->select("-author")->where("_id", "=", 2)->fetch();
```
Output:
```php
[[ "_id" => 2, "title" => "New Select Method", "content" => "Lorem Ipsum" ]]
```
---
## Example 4 - Don't select two fields:
```php
$newsStore->select("-author -title")->where("_id", "=", 2)->fetch();
```
Output:
```php
[[ "_id" => 2, "content" => "Lorem Ipsum" ]]
```
---
## Example 5 - Just select author, without _id field:
```php
$newsStore->select("author -_id")->where("_id", "=", 2)->fetch();
```
Output:
```php
[[ "author" => "Lorem Ipsum" ]]
```
---
## Example 6 - Exclude not existing field:
```php
$newsStore->select("-rating")->where("_id", "=", 2)->fetch();
```
Output:
```php
[
  [
    "title" => "New Select Method",
    "content" => "Lorem Ipsum",
    "author" => "Max",
    "_id" => 2
  ]
]
```
---
## Example 7 - Select not existing field:
```php
$newsStore->select("rating")->where("_id", "=", 2)->fetch();
```
Output:
```php
[[ "_id" => 2 ]]
```

#38 I think this is a good solution for this enhancement request.

**Comment by Timu57** [comment]
#31 

Updated the orWhere method to allow infinite conditions that have an "and" between each condition.

Now the orWhere method can be used in four ways:

## "Old way"
```php
$newsStore->where("_id", "=", 2)->orWhere("author", "=", "Max")->fetch();
```
## With arrays
```php
$condition1 = ["author", "=", "Max"];
$condition2 = ["author", "=", "Isabelle"];
$newsStore->where("_id", "=", 2)->orWhere($condition1, $condition2)->fetch();
```
## With maps
```php
$condition1 = ["fieldName" => "author", "condition" => "=", "value" => "Max"];
$condition2 = ["fieldName" => "author", "condition" => "=", "value" => "Isabelle"];
$newsStore->where("_id", "=", 2)->orWhere($condition1, $condition2)->fetch();
```
## Mix of array and map
```php
$condition1 = ["author", "=", "Max"];
$condition2 = ["fieldName" => "author","condition" =>  "=", "value" => "Isabelle"];
$newsStore->where("_id", "=", 2)->orWhere($condition1, $condition2)->fetch();
```

**Comment by Timu57** [comment]
#30 
Updated getStoreId method to use flock. This prevents duplicate _id

**Comment by rakibtg** [comment]
@Timu57 Many thanks for your contributions, it's inspiring. I am all booked till this Sunday, then the first thing I would do is to review your code and merge it right away. Sorry for the delay.

**Here are some quick thoughts:**
The way you have implemented the `select` method is really interesting, we can select or de-select at once like this:
```php
$newsStore->select("author -_id");
```
After a while the first thing I have noticed that it might create confusions, for example some one might have a key called 
```
-name
```
Now if he want to select only name he would write the query like this: (If I understood it correctly)
```php
$newsStore->select("-name");
```
It will work now in opposite direction! Some times it could be also hard to read for other team members.

So, I was thinking of two different methods,
- `select`
- `except`

Making sure,
- They only accepts an array of key names. Not string exploded with a space as "first name" is also valid as a key name!
  ```php
  // Select few fields.
  select(['_id', 'name', 'country'])

  // Exclude fields.
  except(['name'])
  ```

Please let me know what you think about this update. 
Have a nice day!

**Comment by Timu57** [comment]
@rakibtg Thank you for your response.
No problem, take your time.
My inspiration for this implementation was the way mongoose is handling the select.
https://mongoosejs.com/docs/api/query.html#query_Query-select
But I see your point.
I will update the implementation to use arrays instead of a String, to allow keys with space and a minus prepended.

**Comment by Timu57** [comment]
Now the implementation is like this:

```php
// select few fields
$newsStore->select(["title","content"])->where("_id", "=", 2)->fetch();
// exclude fields
$newsStore->except(["_id"])->where("_id", "=", 2)->fetch();
// select and exclude fields
$newsStore->select(["title"])->except(["_id","author"])->where("_id", "=", 2)->fetch();
```

**Comment by Timu57** [comment]
Hi, is something wrong with the pr?

**Comment by rakibtg** [comment]
Hi @Timu57 Extremely sorry for the delay, hopefully I can merge it within tomorrow :)

**Review by rakibtg — APPROVED** [review]

**Comment by rakibtg** [comment]
@Timu57 Merged 🎉  Thanks for the PR ❤️. Going to release soon.

**Comment by Timu57** [comment]
Thank you for merging this PR :smiling_face_with_three_hearts: some open issues are covered by this PR.

#30 #31 #34 #38 

Just wanted to say, that you could consider closing them :smile:

**Pull request merged**
