### PR TITLE
CLI

### PR DESCRIPTION
**Pull request by amcquade**
Added a CLI for managing stores and records. Since this is still a work in progress, I was just hoping to get some feedback before i go about implementing the other functions, let me know what you think!

### CODE REVIEW

**Comment by rakibtg** [comment]
Sorry for late reply, i will review and share my ideas with you tomorrow :)

**Comment by rakibtg** [comment]
Hi @amcquade I was unable to test the functionalities you have envisioned.
```php
php cli.php create-store test1
```
would give a lot of errors! However, I think it could be a very interesting idea to have a simple CLI!
Please let me know your updates.

**Comment by amcquade** [comment]
hey @rakibtg take a look at the [getop documation.](https://www.php.net/manual/en/function.getopt.php) the command is meant to be passed as `php cli.php --create-store test1`. i guess this means i should add a section to the readme and a help argument lol.

**Comment by rakibtg** [comment]
@amcquade Yeah, totally missed it. i'm on a vacation so was not able to look at the code properly .. haha.. never mind

**Comment by rakibtg** [comment]
@amcquade @thehotnspicy This is incredible, i have done a little test and it was working just fine. I think we should move `"league/climate"` as dev-dependency, what do you think?

**Comment by Timu57** [comment]
@amcquade
Hi and thank you for your PR.
I am not quiet sure if SleekDB needs a CLI or not and do you think we can accomplish a CLI without any third party library?
I will close this PR for now. Please feel free to reopen it if there are additions for this feature planned.

**Comment by amcquade** [comment]
@Timu57 we could definitely create a CLI without a third party library, but i dont really see a reason to reinvent the wheel, even if its just a developer feature

**Comment by Timu57** [comment]
Sure you are right.
I think we can merge it into the `feature/cli` branch and release that feature with `Version 2.1`

**Comment by Timu57** [comment]
Thank you for your PR.
Your code looks great!
There are many new features coming with version 2.0.
Hope we can improve on your feature and that you can help us.

**Comment by amcquade** [comment]
@Timu57 awesome! Looking forward to it, let me know how else i can help!

**Pull request merged**
